### ISSUE TITLE
deb Package is missing a description

### ISSUE THREAD

**Issue by czunker** [mondoohq/client#105]
**Is your feature request related to a problem? Please describe.**
The package has no description:
```
mondoo/stable 5.29.1 amd64
  no description given
```

**Describe the solution you'd like**
It would be nice to have a short description. to know this is the mondoo cli client.

**Describe alternatives you've considered**

**Additional context**

**Comment by chris-rock** [comment]
fixed on mondoo 5.29.2, please re-open if you see that issue still happening
