### ISSUE TITLE
Quick start isn't there?

### ISSUE THREAD

**Issue by mattray** [mondoohq/client#112]
After the curl-bash installation the installer reports
```
Mondoo is set up and ready to go!

Follow our quick start guide for next steps: https://mondoo.com/docs/getstarted/quickstart
```
https://mondoo.com/docs/getstarted/quickstart is a 404.

<img width="1240" alt="Screen Shot 2022-03-16 at 6 33 09 PM" src="https://user-images.githubusercontent.com/330023/158539147-ed49959c-f0e4-4bf7-90ea-8932e74fb4eb.png">

**Comment by benr** [comment]
Thanks for the report @mattray

**Comment by benr** [comment]
Redirects for the missing pages (https://mondoo.com/docs/getstarted/overview & https://mondoo.com/docs/server/registration were impacted as well) have been installed and a process for inserting redirects when layout in the docs changes established.
