### ISSUE TITLE
Pop!_OS / Ubuntu 22.04 platform support missing

### ISSUE THREAD

**Issue by stdevel** [mondoohq/client#126]
Hello everyone!
First of all, this is my first bug report - I hope this is the right place and my information is sufficient. Let me know if you need more details.

**Describe the bug**
It looks like Pop!_OS / Ubuntu 22.04 LTS is currently unsupported by Mondoo client. I registered a Pop!_OS 22.04 LTS client (*based on Ubuntu 22.04*) and saw several issues in the Mondoo console - e.g. using `Linux Security Baseline by Mondoo`:

```text
[Query Error]
failed to create resource 'package': could not detect suiteable package manager for platform
```

```text
[Query Error]
failed to create resource 'service': cannot find service manager
```

**To Reproduce**
1. Spin-up a Pop!_OS / Ubuntu 22.04 VM
2. Register it to Mondoo
3. Access Mondoo console and check against `Linux Security Baseline by Mondoo v1.0.0`

**Expected behavior**
Service and package resources should work like for other distros.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/5862725/165231641-2d7621c1-d543-4793-808f-d4a1ecea74fe.png)
![grafik](https://user-images.githubusercontent.com/5862725/165231825-484c062a-7102-4cdb-84ee-5a27b501f486.png)

**Additional context**
This might be related to Pop!_OS only (_didn't test against vanilla Ubuntu 22.04_) as `/etc/os-release` differs from vanilla Ubuntu 22.04.

**Comment by chris-rock** [comment]
Thank you @stdevel Until now we have not recognised Pop!_OS as a variant of Ubuntu. Therefore the `package` and `packages` resource did not detect the packages. Same applies to the `service` resource. We are going to include improvements for Pop!_OS in todays release.

**Comment by stdevel** [comment]
Wow, that was fast - thanks a lot @chris-rock - let me know if I can help testing. 👍🏻

**Comment by atomic111** [comment]
@stdevel mondoo version 5.36.0 is released and includes the fix for your Pop!_OS

```
atomic111:~/Downloads ∅> /bin/mondoo version
Mondoo 5.36.0 (7b702c6, 2022-04-26T13:04:56Z)
atomic111:~/Downloads ∅> /bin/mondoo shell -t docker://58cec7288092
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source --config
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1
                        .-.            
                        : :            
,-.,-.,-. .--. ,-.,-. .-' : .--.  .--. ™
: ,. ,. :' .; :: ,. :' .; :' .; :' .; :
:_;:_;:_;`.__.':_;:_;`.__.'`.__.'`.__.'  interactive shell

mondoo> platform.name
platform.name: "pop"
mondoo> packages.list.where( name == /ssh/)
packages.list.where: [
  0: package id = deb://libssh-4/0.9.3-2ubuntu2.1/amd64
  1: package id = deb://openssh-client/1:8.2p1-4ubuntu0.1/amd64
]
mondoo> 
```

Please test it with our system and provide us feedback

**Comment by stdevel** [comment]
I upgraded the `mondoo` package, restarted the service (_and waited for the next scan_), but still have the same findings:

```text
[Query Error]
failed to create resource 'package': could not detect suiteable package manager for platform
```

```text
[Query Error]
failed to create resource 'service': cannot find service manager
```

I have the same version (`Mondoo 5.36.0 (7b702c6, 2022-04-26T13:04:56Z)`) - what am I missing here?

**Comment by chris-rock** [comment]
Can you the content of `/etc/os-release`?

**Comment by stdevel** [comment]
Good morning @chris-rock,
here is the content:

```
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

In addition, here is the `lsb_release` output:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
```

Hope this helps!

**Comment by chris-rock** [comment]
Not sure :-) Glad it works now. Please let us know if you run into any other issue.
