### ISSUE TITLE
Mishandling of EC2 instances with dangling key-pair associations

### ISSUE THREAD

**Issue by someara** [mondoohq/client#195]
**Describe the bug**

Mondoo client 6.18.0 mishandles the case where an EC2 instance is associated with a non-existent key-pair.

**To Reproduce**

1. Create an EC2 key-pair
2. Create an EC2 instance, using the above key-pair
3. Delete the key-pair
4. DEBUG=1 mondoo shell aws -c aws.ec2.instances

**Screenshots**

![Screenshot 2022-10-10 at 20 33 02](https://user-images.githubusercontent.com/69068/194931465-adddb901-9815-405a-a16c-c66f917d3b99.png)

Each control with an error expands to the same message:

```
[Query Error]
job err: : failed to create resource 'aws.ec2.keypair': operation error EC2: DescribeKeyPairs, https response error StatusCode: 400, RequestID: 5bbc7e9f-78ef-40fa-919d-5b80d2304343, api error InvalidKeyPair.NotFound: The key-pair 'what@ever' does not exist
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Monterey

**Comment by chris-rock** [comment]
We fixed this issue and today's release of the Mondoo Client includes the bugfix.

**Comment by someara** [comment]
Thanks!
-s
